### ISSUE TITLE
ImportError: cannot import name 'dates'

### ISSUE THREAD

**Issue by semerda** [python-babel/flask-babel#124]
Hi, I'm running Flask in docker and keep seeing this error when I try to spin up the container. Can anyone help point me in the right direction?

web_1    | Traceback (most recent call last):
web_1    |   File "./main.py", line 43, in <module>
web_1    |     from flask_babel import Babel, format_datetime
web_1    |   File "/usr/local/lib/python3.6/site-packages/flask_babel/__init__.py", line 18, in <module>
web_1    |     from babel import dates, numbers, support, Locale

I also verified that /usr/local/lib/python3.6/site-packages/ has both babel and flask_babel directories.

Cheers,
Ernest

**Comment by semerda** [comment]
Sorry user error ;-)
