### ISSUE TITLE
Bug application context since v0.10

### ISSUE THREAD

**Issue by yoyoprs** [python-babel/flask-babel#90]
I use flask_script (and flask_migrate) to migrate my sql schema.
Since version 0.10 i got this error.
Everything works well with 0.9

```python
File "/usr/local/lib/python2.7/dist-packages/flask_babel/__init__.py", line 215, in get_translations
  babel = current_app.extensions['babel']
File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 343, in __getattr__
  return getattr(self._get_current_object(), name)
File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 302, in _get_current_object
  return self.__local()
File "/usr/local/lib/python2.7/dist-packages/flask/globals.py", line 34, in _find_app
  raise RuntimeError('working outside of application context')
```

**Comment by TkTech** [comment]
@yoyoprs need the entire stack trace.

**Comment by yoyoprs** [comment]
```python
Traceback (most recent call last):
  File "manage.py", line 6, in <module>
    from webapp import db, app
  File "/var/www/webapp/__init__.py", line 62, in <module>
    from webapp.mod_webdav.views import web_dav
  File "/var/www/webapp/mod_webdav/views.py", line 7, in <module>
    from webapp.controllers import no_guest
  File "/var/www/webapp/controllers/__init__.py", line 11, in <module>
    class FileConstants(object):
  File "/var/www/webapp/controllers/__init__.py", line 20, in FileConstants
    share_suffix_on_duplicate = u'_' + gettext(u'shared')
  File "/usr/local/lib/python2.7/dist-packages/flask_babel/__init__.py", line 538, in gettext
    t = get_translations()
  File "/usr/local/lib/python2.7/dist-packages/flask_babel/__init__.py", line 215, in get_translations
    babel = current_app.extensions['babel']
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 343, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 302, in _get_current_object
    return self.__local()
  File "/usr/local/lib/python2.7/dist-packages/flask/globals.py", line 34, in _find_app
    raise RuntimeError('working outside of application context')
RuntimeError: working outside of application context
```

**Comment by jbaltie** [comment]
Same case here with flask_testing: https://travis-ci.org/jbaltie/ShAuPlHub/builds/128892641
Reverting to 0.9 fixed the issue: https://travis-ci.org/jbaltie/ShAuPlHub/builds/129231830

**Comment by TkTech** [comment]
For the most part, this is people incorrectly using flask-babel without an application context. You've been able to get away with it before because the translations folder was just a hardcoded string, `/translations`. Now, it's a configuration option taken from your app config that allows multiple translation directories.

**Comment by jbaltie** [comment]
Yep you're right !
Many thanks.

**Comment by TkTech** [comment]
@yoyoprs it looks like your error is exactly the same. You need an application context, or you need to use the lazy versions. The fact that this worked in earlier versions without a context is just a side effect.

**Comment by yoyoprs** [comment]
ok for me, i will use lazy method. Thank's you :)

**Comment by jmagnusson** [comment]
@TkTech As I mentioned [here](https://github.com/python-babel/flask-babel/pull/88/files#diff-bc911fbeeca3dde683a5094eeab05796R204) the code clearly states that the function will never fail. So this is definitely a regression. One shouldn't be forced to always have an application context available to run the code. Translations should be accessible and configurable outside as well.
